### ISSUE TITLE
Overclock/Focus aren't granting Movement/Attack bonuses 

### ISSUE THREAD

**Issue by Junopur** [Moffein/HAN-D_OVERCLOCKED#16]
Overclock/Focus aren't granting Movement/Attack bonuses, not sure if another mod could be the cause but it functioned earlier, could be caused by RiskyMod

**Comment by Moffein** [comment]
RiskyMod and HAN-D Overclocked are compatible. If you have HolyDLL, that's likely breaking all of your mods.
If it's not that, then post your LogOutput.log file (Settings -> Locations -> Browse Profile Folder -> BepInEx) and mod profile (Settings -> Profile -> Export Profile as File).

**Comment by Junopur** [comment]
[LogOutput.zip](https://github.com/Moffein/HAN-D_OVERCLOCKED/files/10531116/LogOutput.zip)
[ROR2-2_1675035174092.zip](https://github.com/Moffein/HAN-D_OVERCLOCKED/files/10531120/ROR2-2_1675035174092.zip)

Couldn't find Holy.DLL, also having issue with Miner's passive not working

**Comment by Moffein** [comment]
RiskyMod and FlatItemBuff are conflicting. You can use both at the same time, but you need to go through their configs and make sure they aren't attempting to modify the same item. Check the list of stuff FlatItemBuff modifies, and choose whether you want to disable the RiskyMod changes or the FlatItemBuff changes for each one.

**Comment by Junopur** [comment]
I see, thank you for the help I appreciate it!
